### ISSUE TITLE
[BUG] Fix Praveen's photo

### ISSUE THREAD

**Issue by Panquesito7** [Git-Commit-Show/landing-page#160]
**Description**

Praveen Kumar's photo is very stretched. It should be fixed.

**Screenshots**

![image](https://user-images.githubusercontent.com/51391473/161598686-769d4ffa-a3e9-484e-a264-4ac434deffe0.png)

**Additional context**

Instead of storing the images in a folder, we can use the direct links of their profiles from socials, such as Twitter, GitHub, etc..

**Comment by praveagra** [comment]
There is another photo of the speaker just by the name of Praveen.png

As soon as we replace the img src, the issue will be fixed. I have made the necessary changes and created a merge request.
