### ISSUE TITLE
Git commit show Text and countdown: Reposition and resizing required

### ISSUE THREAD

**Issue by aryan2574** [Git-Commit-Show/landing-page#45]
As from our official design: 
[Official Figma Design](https://www.figma.com/proto/Pcgl4BjxXUY9oveLTPmpVS/Git-Commit-Show?node-id=1%3A2&viewport=369%2C-177%2C0.6467553377151489&scaling=min-zoom)

The text and countdown timer should look like this:
![Figma](https://user-images.githubusercontent.com/40919909/84119635-a732c400-aa02-11ea-9f1f-8d2dd77da672.png)

But It is like this now:

![gitcommitshow](https://user-images.githubusercontent.com/40919909/84119678-b6197680-aa02-11ea-8560-dd693588c152.png)

**Need some resizing and positioning. Also check for this at every screen size and make it responsive.**

**Comment by khandelwalsarvesh** [comment]
i will work on this issue #45
