### ISSUE TITLE
Animation for buttons

### ISSUE THREAD

**Issue by gitcommitshow** [Git-Commit-Show/landing-page#56]
Add a subtle animation for all buttons. 
The animation should be a color change as implemented  [here](https://codepen.io/tyberiu88/pen/YgJGMX) 

Note: we should not change any button style, only the animation needs to be added. (Same shadows as before)

**Comment by aryan2574** [comment]
#56 Issue Working on it.

**Comment by aryan2574** [comment]
Making new changes
