### ISSUE TITLE
Spacing between heading and content is too much in speaker section

### ISSUE THREAD

**Issue by dk-dinesh** [Git-Commit-Show/landing-page#68]
Spacing or gap between the heading GIT COMMIT SHOW 2020 and its content is too much. It needs to be matched with the [Figma design](https://www.figma.com/file/Pcgl4BjxXUY9oveLTPmpVS/Git-Commit-Show) 
![IMG-20200614-WA0002](https://user-images.githubusercontent.com/55187704/84583636-24ea3b80-ae18-11ea-9958-d3a5115796f9.jpg)

**Comment by khandelwalsarvesh** [comment]
working on it #68
