### ISSUE TITLE
Move "Apply to appear on the show" button to its original position as in figma

### ISSUE THREAD

**Issue by dk-dinesh** [Git-Commit-Show/landing-page#70]
Move "Apply to appear on the show" button to its original postion as in [Figma design](https://www.figma.com/file/Pcgl4BjxXUY9oveLTPmpVS/Git-Commit-Show) 
![IMG-20200614-WA0004](https://user-images.githubusercontent.com/55187704/84583921-67ae1280-ae1c-11ea-9504-ec9c9a6478c5.jpg)

**Comment by khandelwalsarvesh** [comment]
working on it #70
