### ISSUE TITLE
Carousel arrows and description alignment is not matching with figma

### ISSUE THREAD

**Issue by dk-dinesh** [Git-Commit-Show/landing-page#71]
Issues related to carousel are mentioned below:-
1. Arrows should not touch the edge of the screen. There should be some margin.
2. Arrows are not positioned correctly. They should be centered vertically (with height of video) as in figma.
3. Text of the description is not aligned as in figma. It should be left aligned w.r.t video as in figma.

![IMG_20200614_091438](https://user-images.githubusercontent.com/55187704/84584264-b4dfb380-ae1f-11ea-8696-5b1115cd2e2c.jpg)

**Comment by aryan2574** [comment]
Working on it
