### ISSUE TITLE
Left part of thumbnail of Daniel's video gets cut out on small devices

### ISSUE THREAD

**Issue by dk-dinesh** [Git-Commit-Show/landing-page#72]
Left part of thumbnail of Daniel's video gets cut out on small devices. When we reduce the size of the window left part of thumbnail gets cut out  and we have to maintain the 16:9 ratio for the video embed.
![IMG-20200614-WA0000](https://user-images.githubusercontent.com/55187704/84584425-e8234200-ae21-11ea-9cd9-a124d7ed9200.jpg)

**Comment by kritikasahni8** [comment]
will be working on this
