### ISSUE TITLE
"Apply to appear on the show" button is not centered for width 350px and less

### ISSUE THREAD

**Issue by dk-dinesh** [Git-Commit-Show/landing-page#78]
"Apply to appear on the show" button is not centered for width 350px and less.
![IMG_20200615_235140](https://user-images.githubusercontent.com/55187704/84703889-97712d80-af76-11ea-9b54-fcb8e369ae11.jpg)

**Comment by dk-dinesh** [comment]
I'm working on this.

**Comment by khandelwalsarvesh** [comment]
working on it #78

**Comment by rh3xp** [comment]
This has been fixed.
