### ISSUE TITLE
Carousel is overlapping after adding margin

### ISSUE THREAD

**Issue by dk-dinesh** [Git-Commit-Show/landing-page#80]
Three issues with carousel:-
1. After adding margin to arrows it start overlapping.
2. Arrows are still not vertically centered as in figma.
3. Space between description and carousel is too much.
![IMG_20200615_235018](https://user-images.githubusercontent.com/55187704/84705548-339c3400-af79-11ea-9255-dfa35feefc2a.jpg)

**Comment by aryan2574** [comment]
Done. Close the issue
